name: Testing

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches:  [ "master" ]

jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                java-version: "17"
                cache: maven
            - name: Run Test
              run: mvn test
            - name: Export test results as a tar file
              run: tar -cvf test-results.tar ./target/karate-reports/
              working-directory: ${{ github.workspace }}
            - name: Update dependency graph
              uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
